### ISSUE TITLE
Dropdown error - addon unusable

### ISSUE THREAD

**Issue by Valfyre** [WoW-MogIt/MogIt#29] opened 2023-11-10 03:56 UTC
15x SharedXML/UIDropDownMenu.lua:91: calling 'GetWindow' on bad self (Usage: local window = self:GetWindow())
[string "=[C]"]: in function `GetWindow'
[string "@SharedXML/UIDropDownMenu.lua"]:91: in function `UIDropDownMenu_Initialize'
[string "@SharedXML/UIDropDownMenu.lua"]:1167: in function <SharedXML/UIDropDownMenu.lua:1024>
[string "=[C]"]: ?
[string "=[C]"]: in function `ToggleDropDownMenu'
[string "@MogIt/Libs/Libra/Dropdown.lua"]:80: in function `ToggleMenu'
[string "@MogIt/Core/GUI.lua"]:563: in function <MogIt/Core/GUI.lua:557>

Locals:
(*temporary) = <table> {
 _displayMode = "MENU"
 active = Button {
 }
 xOffset = 0
 SetHeight = <function> defined @MogIt/Libs/Libra/Dropdown.lua:27
 yOffset = 0
 modules = Button {
 }
 options = Button {
 }
 preview = Button {
 }
 initialize = <function> defined @MogIt/Core/GUI.lua:550
 parent = MogItFrame {
 }
 CreateMenu = <function> defined @MogIt/Core/GUI.lua:582
 tier = <table> {
 }
 catalogue = Button {
 }
}

**Comment by Ketrel** [comment] 2023-11-11 05:28
I did this `git diff -U0 10.1.7 10.2.0 -- UIDropDownMenu.lua `

This is the output
```diff
diff --git a/Interface/SharedXML/UIDropDownMenu.lua b/Interface/SharedXML/UIDropDownMenu.lua
index a715d766..53b42afb 100644
--- a/Interface/SharedXML/UIDropDownMenu.lua
+++ b/Interface/SharedXML/UIDropDownMenu.lua
@@ -90,0 +91 @@ function UIDropDownMenu_Initialize(frame, initFunction, displayMode, level, menu
+       dropDownList:SetWindow(frame:GetWindow());
```

**Comment by Lombra** [comment] 2023-11-11 11:19
Duplicate of #28.

**Closed by Lombra** 2023-11-11 11:19 UTC
